### ISSUE TITLE
ERROR: Unexpected output from "barman list-files"

### ISSUE THREAD

**Issue by Misteur-Z** [2ndquadrant-it/barman#107]
- Ubuntu 16.04
- Kernel `4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 `

- Python 2.7.12

 - Barman:
```
$ apt-cache show barman
Package: barman
Version: 2.1-1.pgdg16.04+1
Architecture: all
Maintainer: Marco Nenciarini <mnencia@debian.org>
Installed-Size: 660
Depends: python-argcomplete, python-argh, python-dateutil, python-psycopg2, python:any (<< 2.8), python:any (>= 2.7.5-5~), adduser, rsync (>= 3.0.4~)
Recommends: openssh-server, openssh-client, postgresql-client | postgresql-client-9.6 | postgresql-client-9.5 | postgresql-client-9.4 | postgresql-client-9.3 | postgresql-client-9.2
Suggests: barman-cli, repmgr (>= 3.2.0)
Homepage: http://www.pgbarman.org
Priority: extra
Section: database
Filename: pool/main/b/barman/barman_2.1-1.pgdg16.04+1_all.deb
Size: 118930
SHA256: 16a0c0ee70762415c4bd9d8e1208b899116ba9bfd7d71e8330c7484324cd344f
SHA1: 6aa2ea835649ab56c972d9111534f5c7964d012b
MD5sum: 85a3c6ee9f94751bcb29dd76fec187c3
Description: Backup and Recovery Manager for PostgreSQL
 Barman (Backup and Recovery Manager) is an open-source
 administration tool for disaster recovery of PostgreSQL
 servers written in Python.
 .
 It allows your organisation to perform remote backups of
 multiple servers in business critical environments to
 reduce risk and help DBAs during the recovery phase.
 .
 Barman is distributed under GNU GPL 3 and maintained
 by 2ndQuadrant.
Description-md5: 3a5b57842a831067f70d5ac6c7b3c460
```
Command used:
`repmgr -verbose -h <postgres_master_ip> -U repmgr -d repmgr -D /var/lib/postgresql/9.6/main standby clone`

Output:
```
NOTICE: looking for configuration file in current directory
NOTICE: looking for configuration file in /etc
NOTICE: configuration file found at: /etc/repmgr.conf
NOTICE: destination directory '/var/lib/postgresql/9.6/main' provided
NOTICE: getting backup from Barman...
ERROR: Unexpected output from "barman list-files": /mnt/extra/barman/review/basebackups/20170530T160208/backup.info

postgres@pg-cluster-1:~/9.6/main$ EXCEPTION: [Errno 32] Broken pipe
See log file for more details.
```

Error in barman.log:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/barman/cli.py", line 1041, in main
    p.dispatch(pre_call=global_config)
  File "/usr/lib/python2.7/dist-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python2.7/dist-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python2.7/dist-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/usr/lib/python2.7/dist-packages/barman/cli.py", line 580, in list_files
    output.info(line, log=False)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 166, in info
    _put('info', message, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 97, in _put
    getattr(_writer, level)(message, *args)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 368, in info
    self._out(message, args)
  File "/usr/lib/python2.7/dist-packages/barman/output.py", line 332, in _out
    print(_format_message(message, args), file=sys.stdout)

```
Content of `/mnt/extra/barman/review/basebackups/20170530T160208/backup.info`
```
backup_label=None
begin_offset=40
begin_time=2017-05-30 16:02:08+00:00
begin_wal=0000000200000037000000EC
begin_xlog=37/EC000028
config_file=/etc/postgresql/9.6/main/postgresql.conf
deduplicated_size=58211135370
end_offset=96
end_time=2017-05-30 16:02:08.352762+00:00
end_wal=0000000200000037000000F2
end_xlog=37/F2000060
error=None
hba_file=/etc/postgresql/9.6/main/pg_hba.conf
ident_file=/etc/postgresql/9.6/main/pg_ident.conf
included_files=['/etc/postgresql/9.6/main/postgresql.effilab.conf']
mode=postgres
pgdata=/var/lib/postgresql/9.6/main
server_name=review
size=58211135370
status=DONE
tablespaces=None
timeline=2
version=90602
```

**I fixed the error by updating manually with pip all my python modules.**

Before:
```
appdirs (1.4.3)
argcomplete (1.0.0)
argh (0.26.1)
barman (2.1)
barman-cli (1.2)
packaging (16.8)
pip (9.0.1)
psycopg2 (2.6.1)
pyparsing (2.2.0)
python-apt (1.1.0b1)
python-dateutil (2.4.2)
setuptools (35.0.2)
six (1.10.0)
wheel (0.29.0)
```
After:
```
appdirs (1.4.3)
argcomplete (1.8.2)
argh (0.26.2)
barman (2.1)
barman-cli (1.2)
packaging (16.8)
pip (9.0.1)
psycopg2 (2.7.1)
pyparsing (2.2.0)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
setuptools (35.0.2)
six (1.10.0)
wheel (0.29.0)
```
I didn't take time to exactly point out which module needed to be updated sorry, but I think there might be a missing python module dependency ?

**Comment by mnencia** [comment]
From what you have posted, it doesn't looks looks like an error in barman.

The traceback you posted says that the barman process standard output has been closed unexpectedly by repmgr, so it looks like that the barman output triggered an error in repmgr.

Are you sure that all you did to solve the issue is to upgrade the the python modules? The only difference I see are unrelated.

``` diff
 appdirs (1.4.3)
-argcomplete (1.0.0)
-argh (0.26.1)
+argcomplete (1.8.2)
+argh (0.26.2)
 barman (2.1)
 barman-cli (1.2)
 packaging (16.8)
 pip (9.0.1)
-psycopg2 (2.6.1)
+psycopg2 (2.7.1)
 pyparsing (2.2.0)
 python-apt (1.1.0b1)
-python-dateutil (2.4.2)
+python-dateutil (2.6.0)
 setuptools (35.0.2)
 six (1.10.0)
 wheel (0.29.0)
```

**Comment by david-dumas** [comment]
Yes, the only thing I did to solve this was to upgrade manually all the python modules. I can't reproduce the problem any more, sorry.

But there was definitely a problem with parsing the file `/mnt/extra/barman/review/basebackups/20170530T160208/backup.info`, maybe the time stamps?

**Comment by gciolli** [comment]
That error means that repmgr was unable to remove the prefix from the file path, when detecting the backup ID. It seems unrelated to Python updates.
My guess is that the barman configuration for that server change between the two attempts, and in particular the "basebackups_directory" setting.
Summing up, this looks like a repmgr issue; I will open an issue there. Thanks for reporting it.

**Comment by gciolli** [comment]
I have reported the issue and pushed a fix, which needs to be tested.
https://github.com/2ndQuadrant/repmgr/pull/313

**Comment by david-dumas** [comment]
I guess we can close this issue, I don't know if your fix got tested @gciolli .

**Comment by gciolli** [comment]
I think it will be tested as part of the process for the next minor release; perhaps it is better to leave the issue open until then.
However @david-dumas if you have a chance to test it, for instance in the same environment where you found the bug, please report it here.

**Comment by david-dumas** [comment]
Reproduced the problem with barman `2.2` and repmgr `3.3.2`, fixed  `/etc/barman.d/review.conf`.

**Error:**
```
ERROR: Unexpected output from "barman list-files": /mnt/extra/barman/review/basebackups/20170822T151409/backup.info
```

**Before:**
```
incoming_wals_directory = /mnt/extra/barman/review/incoming_wals
errors_directory = /mnt/extra/barman/review/errors
backup_directory = /mnt/extra/barman/review/backup
basebackups_directory = /mnt/extra/barman/review/basebackups
streaming_wals_directory = /mnt/extra/barman/review/streaming_wals
wals_directory = /mnt/extra/barman/review/wals
```
**After => fixed using default folder names:**
```
incoming_wals_directory = /mnt/extra/barman/review/incoming
errors_directory = /mnt/extra/barman/review/errors
backup_directory = /mnt/extra/barman/review
basebackups_directory = /mnt/extra/barman/review/base
streaming_wals_directory = /mnt/extra/barman/review/streaming
wals_directory = /mnt/extra/barman/review/wals
```
**Stopped everything and renamed folders:**
`/mnt/extra/barman/review/basebackups` => `/mnt/extra/barman/review/base`
`/mnt/extra/barman/review/streaming_wals` => `/mnt/extra/barman/review/streaming`
`/mnt/extra/barman/review/incoming_wals` => ` /mnt/extra/barman/review/incoming`

**Comment by gbartolini** [comment]
Hi @david-dumas, thanks for posting. Can you please confirm the issue is still present with latest Barman code from master? Thanks.

**Comment by Misteur-Z** [comment]
* Repmgr `4.0.5-1.pgdg16.04+1`
* Barman `2.3-2.pgdg16.04+1`

Using the default folder names in my last comment for base, streaming and incoming, running ok.

**Comment by wasiualhasib** [comment]
I am also unable to clone from barman showing below error. I am not sure where is the issue. Log not showing that much of details. 

![image](https://user-images.githubusercontent.com/48445960/164404947-eff75e78-5c86-45da-ac1a-8ea2c4063ab9.png)
