### ISSUE TITLE
replication-status:  EXCEPTION: float() argument must be a string or a number

### ISSUE THREAD

**Issue by vfiset** [2ndquadrant-it/barman#135]
when running `replication-status` I get:

    barman@ip-host:/$ barman replication-status db
    Status of streaming clients for server 'db':
      Current LSN on master: 0/2534DFF8
      Number of streaming clients: 1

      1. Async WAL streamer
         Application name: barman_receive_wal
         Sync stage      : 1/3 1-safe
         Communication   : TCP/IP
         IP Address      : host / Port: 38794 / Host: -
         User name       : barman-stream-user
         Current state   : streaming (async)
         Replication slot: barman
         WAL sender PID  : 493
         Started at      : 2017-12-20 16:02:33.935070+00:00
    EXCEPTION: float() argument must be a string or a number
    See log file for more details.

full py stack:

    2017-12-20 16:04:23,107 [319] barman.cli ERROR: float() argument must be a string or a number
    See log file for more details.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/barman/cli.py", line 1123, in main
        p.dispatch(pre_call=global_config)
      File "/usr/lib/python2.7/dist-packages/argh/helpers.py", line 55, in dispatch
        return dispatch(self, *args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/argh/dispatching.py", line 174, in dispatch
        for line in lines:
      File "/usr/lib/python2.7/dist-packages/argh/dispatching.py", line 277, in _execute_command
        for line in result:
      File "/usr/lib/python2.7/dist-packages/argh/dispatching.py", line 231, in _call
        result = function(namespace_obj)
      File "/usr/lib/python2.7/dist-packages/barman/cli.py", line 294, in replication_status
        server.replication_status(args.target)
      File "/usr/lib/python2.7/dist-packages/barman/server.py", line 1976, in replication_status
        standby_info)
      File "/usr/lib/python2.7/dist-packages/barman/output.py", line 255, in result
        _dispatch(_writer, 'result', command, *args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/barman/output.py", line 128, in _dispatch
        return handler(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/barman/output.py", line 868, in result_replication_status
        pretty_size(sent_diff))
      File "/usr/lib/python2.7/dist-packages/barman/utils.py", line 138, in pretty_size
        size = float(size)
    TypeError: float() argument must be a string or a number

**Comment by vfiset** [comment]
Important detail I just realized, I had this error when trying to run `replication-status` on an instance in recovery. This lessens a lot the importance of this issue

**Comment by gbartolini** [comment]
Fixed by ea82717db8e0cbddbe691e1012d47f85c8694c1d
