### ISSUE TITLE
backups failing with python error

### ISSUE THREAD

**Issue by plockaby** [2ndquadrant-it/barman#14]
Another failing backup problem. We're seeing this pretty often, too. This is backing up a postgres 9.1.9 instance with barman 1.5.1 running with Python 2.6.6 (system python on Centos6) installed using pip.

    2015-11-23 01:00:54,147 [8642] barman.backup_executor INFO: Copy done.
    2015-11-23 01:00:54,151 [8642] barman.backup_executor INFO: Asking PostgreSQL server to finalize the backup.
    2015-11-23 01:00:54,839 [8642] barman.backup ERROR: Backup failed issuing start backup command.
    DETAILS: Cannot terminate exclusive backup. You might have to  manually execute pg_stop_backup() on your PostgreSQL server
    2015-11-23 01:00:55,455 [32660] barman.cli ERROR: 'NoneType' object has no attribute 'rfind'
    See log file for more details.
    Traceback (most recent call last):
      File "/usr/local/barman/lib/python2.6/site-packages/barman-1.5.1-py2.6.egg/barman/cli.py", line 865, in main
        p.dispatch(pre_call=global_config)
      File "build/bdist.linux-x86_64/egg/argh/helpers.py", line 55, in dispatch
        return dispatch(self, *args, **kwargs)
      File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 174, in dispatch
        for line in lines:
      File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 277, in _execute_command
        for line in result:
      File "build/bdist.linux-x86_64/egg/argh/dispatching.py", line 231, in _call
        result = function(namespace_obj)
      File "/usr/local/barman/lib/python2.6/site-packages/barman-1.5.1-py2.6.egg/barman/cli.py", line 470, in list_files
        for line in backup_id.get_list_of_files(args.target):
      File "/usr/local/barman/lib/python2.6/site-packages/barman-1.5.1-py2.6.egg/barman/infofile.py", line 524, in get_list_of_files
        for x in self.get_required_wal_segments():
      File "/usr/local/barman/lib/python2.6/site-packages/barman-1.5.1-py2.6.egg/barman/xlog.py", line 163, in enumerate_segments
        end_tli, end_log, end_seg = decode_segment_name(end)
      File "/usr/local/barman/lib/python2.6/site-packages/barman-1.5.1-py2.6.egg/barman/xlog.py", line 125, in decode_segment_name
        name = os.path.basename(path)
      File "/usr/lib64/python2.6/posixpath.py", line 111, in basename
        i = p.rfind('/') + 1
    AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by plockaby** [comment]
You responded that the actual error here is that the call to pg_stop_backup failed. Then I have a hook that automatically calls list-files which fails with the Python error because the backup failed. The rsync for the host in question typically takes about four hours. Would the postgres connection timeout during this period? Is it possible to have something ping the connection to ensure that it is alive during the rsync?

**Comment by plockaby** [comment]
Indeed, the SSH key warning was causing this error, too. Since fixing that (from issue #13) I have not seen this error arise again, either. Thanks again for pointing out my mistake.
