### ISSUE TITLE
cifs not working for wal archive

### ISSUE THREAD

**Issue by ali-joumma** [2ndquadrant-it/barman#228]
Hi,

I've noticed that WAL archiving fails if the WAL directory is pointing to a CIFS mount,
with this error:

2019-05-30 15:38:02,713 [26536] barman.cli ERROR: [Errno 13] Permission denied
See log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 1351, in main
    p.dispatch(pre_call=global_config)
  File "/usr/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/usr/lib/python2.7/site-packages/barman/cli.py", line 928, in archive_wal
    server.archive_wal()
  File "/usr/lib/python2.7/site-packages/barman/server.py", line 1846, in archive_wal
    self.backup_manager.archive_wal(verbose)
  File "/usr/lib/python2.7/site-packages/barman/backup.py", line 567, in archive_wal
    archiver.archive(verbose)
  File "/usr/lib/python2.7/site-packages/barman/wal_archiver.py", line 196, in archive
    self.archive_wal(compressor, wal_info)
  File "/usr/lib/python2.7/site-packages/barman/wal_archiver.py", line 348, in archive_wal
    fsync_file(dst_file)
  File "/usr/lib/python2.7/site-packages/barman/utils.py", line 330, in fsync_file
    os.fsync(file_fd)

so I simply went to /usr/lib/python2.7/site-packages/barman/utils.py
and at line 328, I've changed "os.O_RDONLY" to "os.O_RDWR"
and now it's working fine.

is there a reason why you guys are using O_RDONLY instead of O_RDWR? I'm just asking to make sure that my "fix" didn't actually silently broke something else

Thank you,
Ali

**Comment by lapin-b** [comment]
Hello,

To provide some context, I have the same issue with Hetzner's storage box mounted on CIFS.

I've applied then fix that @ali-joumma has put in their message. Works much better. Now, did that modification break something else ?

Cheers
