### ISSUE TITLE
'>=' not supported between instances of 'str' and 'NoneType'

### ISSUE THREAD

**Issue by GMoustacky** [2ndquadrant-it/barman#262]
Hello team,

I'm recently trying to deploy Barman 2.10 on my PSQL 12 database, everything in Docker containers.

I'm currently on a test setup with 1 master + 1 node using streaming replication on which Barman is pointing to. Data is generated continuously with an insert every 0.1 second and Barman cron is doing its own streaming replication in the background.

Doing a check at startup is all green:

```
Server pg_cluster:
	PostgreSQL: OK
	is_superuser: OK
	PostgreSQL streaming: OK
	wal_level: OK
	replication slot: OK
	directories: OK
	retention policy settings: OK
	backup maximum age: OK (no last_backup_maximum_age provided)
	compression settings: OK
	failed backups: OK (there are 0 failed backups)
	minimum redundancy requirements: OK (have 0 backups, expected at least 0)
	pg_basebackup: OK
	pg_basebackup compatible: OK
	pg_basebackup supports tablespaces mapping: OK
	systemid coherence: OK
	pg_receivexlog: OK
	pg_receivexlog compatible: OK
	receive-wal running: OK
	archiver errors: OK
```

And looking at the replication status, it looks normal:

```
Status of streaming clients for server 'pg_cluster':
  Current LSN on master: 0/244F30E0
  Number of streaming clients: 1

  1. Async WAL streamer
     Application name: barman_receive_wal
     Sync stage      : 2/3 WAL Sent (min)
     Communication   : TCP/IP
     IP Address      : 172.23.0.5 / Port: 33034 / Host: -
     User name       : replicationuser
     Current state   : streaming (async)
     Replication slot: barman
     WAL sender PID  : 213
     Started at      : 2020-01-02 06:27:48.115392+00:00
     Sent LSN   : 0/3FE6EA78 (diff: 0 B)
     Write LSN  : 0/3FE63C60 (diff: -43.5 KiB)
     Flush LSN  : 0/3F000000 (diff: -14.4 MiB)
```

Now I'd like to run a backup with `backup pg_cluster --wait --wait-timeout 300` and after some time I get the following error:
```
root@4ef389593b40:/# /usr/bin/barman backup pg_cluster --wait --wait-timeout 60
Starting backup using postgres method for server pg_cluster in /var/backups/base/20200102T063351
Backup start at LSN: 0/24FE0A50
Starting backup copy via pg_basebackup for 20200102T063351
Copy done (time: 23 seconds)
Finalising the backup.
This is the first backup for server pg_cluster
Backup size: 174.4 MiB
Backup end at LSN: 0/2527CFC0 (000000010000000000000025, 0027CFC0)
Backup completed (start time: 2020-01-02 06:33:51.886146, elapsed time: 25 seconds)
Waiting for the WAL file 000000010000000000000025 from server 'pg_cluster' (max: 60 seconds)
ERROR: The WAL file 000000010000000000000025 has not been received in 60 seconds
```

Looking at the logs for the stacktrace:
```
2020-01-02 06:19:46,431 [232] barman.cli ERROR: '>=' not supported between instances of 'str' and 'NoneType'
See log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/barman/cli.py", line 1355, in main
    p.dispatch(pre_call=global_config)
  File "/usr/lib/python3/dist-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python3/dist-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python3/dist-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/usr/lib/python3/dist-packages/barman/cli.py", line 813, in delete
    if not server.delete_backup(backup_id):
  File "/usr/lib/python3/dist-packages/barman/server.py", line 1130, in delete_backup
    deleted = self.backup_manager.delete_backup(backup)
  File "/usr/lib/python3/dist-packages/barman/backup.py", line 327, in delete_backup
    timelines_to_protect):
  File "/usr/lib/python3/dist-packages/barman/backup.py", line 961, in remove_wal_before_backup
    keep |= wal_info.name >= backup_info.begin_wal
TypeError: '>=' not supported between instances of 'str' and 'NoneType'
```

I also have this repeating line during the wait:
```
2020-01-02 06:42:42,115 [136] barman.wal_archiver INFO: No xlog segments found from streaming for pg_cluster.
```

Where it becomes annoying, is that I have these failed backups that I can't remove:
```
root@4ef389593b40:/# barman list-backup pg_cluster
pg_cluster 20200102T062914 - FAILED
root@4ef389593b40:/# barman delete pg_cluster 20200102T062914
Deleting backup 20200102T062914 for server pg_cluster
Delete associated WAL segments:
EXCEPTION: '>=' not supported between instances of 'str' and 'NoneType'
See log file for more details.
```

If I create a new backup that ends up failing, I will be able to delete it anyway. But this first one can't be deleted at all. Newlines added for readability.
```
root@4ef389593b40:/# /usr/bin/barman backup pg_cluster --wait --wait-timeout 300
Starting backup using postgres method for server pg_cluster in /var/backups/base/20200102T063958
Backup start at LSN: 0/297B3CE8
Starting backup copy via pg_basebackup for 20200102T063958
Copy done (time: 24 seconds)
Finalising the backup.
This is the first backup for server pg_cluster
Backup size: 176.7 MiB
Backup end at LSN: 0/2A9273B8 (00000001000000000000002A, 009273B8)
Backup completed (start time: 2020-01-02 06:39:59.011812, elapsed time: 25 seconds)
Waiting for the WAL file 00000001000000000000002A from server 'pg_cluster' (max: 300 seconds)
Processing xlog segments from streaming for pg_cluster
	00000001000000000000003F
ERROR: The WAL file 00000001000000000000002A has not been received in 300 seconds


root@4ef389593b40:/# barman list-backup pg_cluster
pg_cluster 20200102T063958 - FAILED
pg_cluster 20200102T062914 - FAILED


root@4ef389593b40:/# barman delete pg_cluster 20200102T062914
Deleting backup 20200102T062914 for server pg_cluster
Delete associated WAL segments:
EXCEPTION: '>=' not supported between instances of 'str' and 'NoneType'
See log file for more details.


root@4ef389593b40:/# barman delete pg_cluster 20200102T063958
Deleting backup 20200102T063958 for server pg_cluster
Delete associated WAL segments:
Deleted backup 20200102T063958 (start time: Thu Jan  2 06:46:22 2020, elapsed time: less than one second)


root@4ef389593b40:/# barman list-backup pg_cluster
pg_cluster 20200102T062914 - FAILED
```

My config if it helps:
```root@4ef389593b40:/# cat /etc/barman.conf
[barman]
barman_user = barman
configuration_files_directory = /etc/barman.d
barman_home = /var/lib/barman/
log_file = '/var/log/barman/barman.log'
log_level = INFO
compression = gzip
basebackup_retry_times = 10
parallel_jobs = 4
```

```
root@4ef389593b40:/# cat /etc/barman.d/pgcluster.conf
[pg_cluster]
description = 'Cluster pg_cluster replication'
backup_method = postgres
backup_options = concurrent_backup
streaming_archiver = on
streaming_archiver_name = barman_receive_wal
streaming_archiver_batch_size = 50
streaming_conninfo = host=postgres-2 user=replicationuser password=abcde port=5432
conninfo = host=postgres-2 user=data_admin password=abcde port=5432 connect_timeout=20
slot_name = barman
backup_directory = /var/backups
retention_policy = RECOVERY WINDOW OF 7 DAYS
```

Let me know if you need more details.

**Comment by mnencia** [comment]
Thanks for the report.

You hit at least two bugs:

1. When the wait timeout is hit, it should not mark the backup as failed, but only as WAITING_FOR_WAL
2. Even on a failed or corrupted backup, the `barman delete` command should do its work.

**Comment by mnencia** [comment]
Could you please attach the output of `barman diagnose` command?

**Comment by GMoustacky** [comment]
After restarting the container and starting afresh with Barman, I get the expected output:
```
barman@292cd2a4b885:~$ barman backup pg_cluster --wait --wait-timeout 30
Starting backup using postgres method for server pg_cluster in /var/backups/base/20200106T013323
Backup start at LSN: 0/2B000060
Starting backup copy via pg_basebackup for 20200106T013323
Copy done (time: 30 seconds)
Finalising the backup.
Backup size: 291.0 MiB
Backup end at LSN: 0/2B000060 (00000001000000000000002B, 00000060)
Backup completed (start time: 2020-01-06 01:33:23.788943, elapsed time: 32 seconds)
Waiting for the WAL file 00000001000000000000002B from server 'pg_cluster' (max: 30 seconds)
ERROR: The WAL file 00000001000000000000002B has not been received in 30 seconds
WARNING: IMPORTANT: this backup is classified as WAITING_FOR_WALS, meaning that Barman has not received yet all the required WAL files for the backup consistency.
This is a common behaviour in concurrent backup scenarios, and Barman automatically set the backup as DONE once all the required WAL files have been archived.
Hint: execute the backup command with '--wait'
```

Here is the diagnose output:
```
{
    "global": {
        "config": {
            "barman_home": "/var/lib/barman/",
            "barman_user": "barman",
            "basebackup_retry_times": "10",
            "compression": "gzip",
            "configuration_files_directory": "/etc/barman.d",
            "errors_list": [],
            "log_file": "'/var/log/barman/barman.log'",
            "log_level": "INFO",
            "parallel_jobs": "4"
        },
        "system_info": {
            "barman_ver": "2.10",
            "kernel_ver": "Linux 292cd2a4b885 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux",
            "python_ver": "",
            "release": "Debian GNU/Linux 10.2",
            "rsync_ver": "rsync  version 3.1.3  protocol version 31",
            "ssh_ver": "",
            "timestamp": "Mon Jan  6 01:42:24 2020"
        }
    },
    "servers": {
        "pg_cluster": {
            "backups": {
                "20200106T013157": {
                    "backup_id": "20200106T013157",
                    "backup_label": null,
                    "begin_offset": 13754352,
                    "begin_time": "Mon Jan  6 01:31:57 2020",
                    "begin_wal": "00000001000000000000002A",
                    "begin_xlog": "0/2AD1DFF0",
                    "config_file": "/var/lib/postgresql/data/postgresql.conf",
                    "copy_stats": {
                        "copy_time": 25.526425,
                        "total_time": 25.526425
                    },
                    "deduplicated_size": 305103101,
                    "end_offset": 96,
                    "end_time": "Mon Jan  6 01:32:22 2020",
                    "end_wal": "00000001000000000000002B",
                    "end_xlog": "0/2B000060",
                    "error": null,
                    "hba_file": "/var/lib/postgresql/data/pg_hba.conf",
                    "ident_file": "/var/lib/postgresql/data/pg_ident.conf",
                    "included_files": [
                        "/var/lib/postgresql/data/postgresql.auto.conf"
                    ],
                    "mode": "postgres",
                    "pgdata": "/var/lib/postgresql/data",
                    "server_name": "pg_cluster",
                    "size": 305103101,
                    "status": "WAITING_FOR_WALS",
                    "systemid": "6778506117642125340",
                    "tablespaces": null,
                    "timeline": 1,
                    "version": 120001,
                    "xlog_segment_size": 16777216
                },
                "20200106T013234": {
                    "backup_id": "20200106T013234",
                    "backup_label": null,
                    "begin_offset": 13754352,
                    "begin_time": "Mon Jan  6 01:32:34 2020",
                    "begin_wal": "00000001000000000000002A",
                    "begin_xlog": "0/2AD1DFF0",
                    "config_file": "/var/lib/postgresql/data/postgresql.conf",
                    "copy_stats": {
                        "copy_time": 27.244353,
                        "total_time": 27.244353
                    },
                    "deduplicated_size": 305103101,
                    "end_offset": 96,
                    "end_time": "Mon Jan  6 01:33:01 2020",
                    "end_wal": "00000001000000000000002B",
                    "end_xlog": "0/2B000060",
                    "error": null,
                    "hba_file": "/var/lib/postgresql/data/pg_hba.conf",
                    "ident_file": "/var/lib/postgresql/data/pg_ident.conf",
                    "included_files": [
                        "/var/lib/postgresql/data/postgresql.auto.conf"
                    ],
                    "mode": "postgres",
                    "pgdata": "/var/lib/postgresql/data",
                    "server_name": "pg_cluster",
                    "size": 305103101,
                    "status": "WAITING_FOR_WALS",
                    "systemid": "6778506117642125340",
                    "tablespaces": null,
                    "timeline": 1,
                    "version": 120001,
                    "xlog_segment_size": 16777216
                },
                "20200106T013323": {
                    "backup_id": "20200106T013323",
                    "backup_label": null,
                    "begin_offset": 13754352,
                    "begin_time": "Mon Jan  6 01:33:23 2020",
                    "begin_wal": "00000001000000000000002A",
                    "begin_xlog": "0/2AD1DFF0",
                    "config_file": "/var/lib/postgresql/data/postgresql.conf",
                    "copy_stats": {
                        "copy_time": 30.50775,
                        "total_time": 30.50775
                    },
                    "deduplicated_size": 305103101,
                    "end_offset": 96,
                    "end_time": "Mon Jan  6 01:33:54 2020",
                    "end_wal": "00000001000000000000002B",
                    "end_xlog": "0/2B000060",
                    "error": null,
                    "hba_file": "/var/lib/postgresql/data/pg_hba.conf",
                    "ident_file": "/var/lib/postgresql/data/pg_ident.conf",
                    "included_files": [
                        "/var/lib/postgresql/data/postgresql.auto.conf"
                    ],
                    "mode": "postgres",
                    "pgdata": "/var/lib/postgresql/data",
                    "server_name": "pg_cluster",
                    "size": 305103101,
                    "status": "WAITING_FOR_WALS",
                    "systemid": "6778506117642125340",
                    "tablespaces": null,
                    "timeline": 1,
                    "version": 120001,
                    "xlog_segment_size": 16777216
                }
            },
            "config": {
                "active": true,
                "archiver": false,
                "archiver_batch_size": 0,
                "backup_directory": "/var/backups",
                "backup_method": "postgres",
                "backup_options": "concurrent_backup",
                "bandwidth_limit": null,
                "barman_home": "/var/lib/barman/",
                "barman_lock_directory": "/var/lib/barman/",
                "basebackup_retry_sleep": 30,
                "basebackup_retry_times": 10,
                "basebackups_directory": "/var/backups/base",
                "check_timeout": 30,
                "compression": "gzip",
                "conninfo": "host=postgres-2 user=data_admin password=*REDACTED* port=5432 connect_timeout=20",
                "create_slot": "manual",
                "custom_compression_filter": null,
                "custom_decompression_filter": null,
                "description": "Cluster pg_cluster replication",
                "disabled": false,
                "errors_directory": "/var/backups/errors",
                "immediate_checkpoint": false,
                "incoming_wals_directory": "/var/backups/incoming",
                "last_backup_maximum_age": null,
                "max_incoming_wals_queue": null,
                "minimum_redundancy": 0,
                "msg_list": [],
                "name": "pg_cluster",
                "network_compression": false,
                "parallel_jobs": 4,
                "path_prefix": null,
                "post_archive_retry_script": null,
                "post_archive_script": null,
                "post_backup_retry_script": null,
                "post_backup_script": "/var/lib/barman/post_backup_script.sh",
                "post_delete_retry_script": null,
                "post_delete_script": null,
                "post_recovery_retry_script": null,
                "post_recovery_script": null,
                "post_wal_delete_retry_script": null,
                "post_wal_delete_script": null,
                "pre_archive_retry_script": null,
                "pre_archive_script": null,
                "pre_backup_retry_script": null,
                "pre_backup_script": null,
                "pre_delete_retry_script": null,
                "pre_delete_script": null,
                "pre_recovery_retry_script": null,
                "pre_recovery_script": null,
                "pre_wal_delete_retry_script": null,
                "pre_wal_delete_script": null,
                "primary_ssh_command": null,
                "recovery_options": "",
                "retention_policy": "window 7 d",
                "retention_policy_mode": "auto",
                "reuse_backup": null,
                "slot_name": "barman",
                "ssh_command": null,
                "streaming_archiver": true,
                "streaming_archiver_batch_size": 50,
                "streaming_archiver_name": "barman_receive_wal",
                "streaming_backup_name": "barman_streaming_backup",
                "streaming_conninfo": "host=postgres-2 user=replicationuser password=*REDACTED* port=5432",
                "streaming_wals_directory": "/var/backups/streaming",
                "tablespace_bandwidth_limit": null,
                "wal_retention_policy": "simple-wal 7 d",
                "wals_directory": "/var/backups/wals"
            },
            "status": {
                "archive_timeout": 0,
                "checkpoint_timeout": 300,
                "config_file": "/var/lib/postgresql/data/postgresql.conf",
                "connection_error": null,
                "current_lsn": "0/2B000148",
                "current_size": 304850095.0,
                "current_xlog": null,
                "data_checksums": "off",
                "data_directory": "/var/lib/postgresql/data",
                "hba_file": "/var/lib/postgresql/data/pg_hba.conf",
                "hot_standby": "on",
                "ident_file": "/var/lib/postgresql/data/pg_ident.conf",
                "included_files": [
                    "/var/lib/postgresql/data/postgresql.auto.conf"
                ],
                "is_in_recovery": true,
                "is_superuser": true,
                "max_replication_slots": "10",
                "max_wal_senders": "8",
                "pg_basebackup_bwlimit": true,
                "pg_basebackup_compatible": true,
                "pg_basebackup_installed": true,
                "pg_basebackup_path": "/usr/bin/pg_basebackup",
                "pg_basebackup_tbls_mapping": true,
                "pg_basebackup_version": "12.1-1.pgdg100+1)",
                "pg_receivexlog_compatible": true,
                "pg_receivexlog_installed": true,
                "pg_receivexlog_path": "/usr/bin/pg_receivewal",
                "pg_receivexlog_supports_slots": true,
                "pg_receivexlog_synchronous": false,
                "pg_receivexlog_version": "12.1-1.pgdg100+1)",
                "pgespresso_installed": false,
                "postgres_systemid": "6778506117642125340",
                "replication_slot": [
                    "barman",
                    true,
                    "0/2B000000"
                ],
                "replication_slot_support": true,
                "server_txt_version": "12.1",
                "streaming": true,
                "streaming_supported": true,
                "streaming_systemid": "6778506117642125340",
                "synchronous_standby_names": [
                    ""
                ],
                "timeline": 1,
                "wal_compression": "on",
                "wal_level": "replica",
                "xlog_segment_size": 16777216,
                "xlogpos": "0/2B000148"
            },
            "wals": {
                "last_archived_wal_per_timeline": {
                    "00000001": {
                        "compression": "gzip",
                        "name": "00000001000000000000002A",
                        "size": 4717204,
                        "time": 1578274296.0
                    }
                }
            }
        }
    }
}
```

I assume the issue is only happening in specific circumstances.
