### ISSUE TITLE
EXCEPTION: [Errno 13] Permission denied: '/tmp/barman_recovery-aYBKVi/postgresql.conf

### ISSUE THREAD

**Issue by jacekjaros** [2ndquadrant-it/barman#68]
when  I try to recover backup i get following error:
```
[root@barman-qa-01 ~]# barman recover --remote-ssh-command 'ssh postgres@barman-qa-02' test-01 20161107T124401 /var/lib/pgsql/9.5/data/
Starting remote restore for server test-01 using backup 20161107T124401
Destination directory: /var/lib/pgsql/9.5/data/
Copying the base backup.
Copying required WAL segments.
Generating archive status files
Identify dangerous settings in destination directory.
EXCEPTION: [Errno 13] Permission denied: '/tmp/barman_recovery-aYBKVi/postgresql.conf'
See log file for more details.
```

barman.log:
```
2016-11-08 15:38:30,903 [6715] barman.command_wrappers DEBUG: Command: "ssh postgres@barman-qa-02 'test -d /var/lib/pgsql/9.5/data/pg_xlog/archive_status'"
2016-11-08 15:38:31,062 [6715] barman.command_wrappers DEBUG: Command return code: 0
2016-11-08 15:38:31,063 [6715] barman.command_wrappers DEBUG: Command stdout:
2016-11-08 15:38:31,063 [6715] barman.command_wrappers DEBUG: Command stderr:
2016-11-08 15:38:31,065 [6715] barman.recovery_executor INFO: Identify dangerous settings in destination directory.
2016-11-08 15:38:31,067 [6715] barman.cli ERROR: [Errno 13] Permission denied: '/tmp/barman_recovery-Yd5gHN/postgresql.conf'
See log file for more details.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/barman/cli.py", line 1022, in main
    p.dispatch(pre_call=global_config)
  File "/usr/lib/python2.6/site-packages/argh/helpers.py", line 47, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/argh/dispatching.py", line 121, in dispatch
    for line in lines:
  File "/usr/lib/python2.6/site-packages/argh/dispatching.py", line 197, in _execute_command
    for line in result:
  File "/usr/lib/python2.6/site-packages/argh/dispatching.py", line 153, in _call
    result = args.function(args)
  File "/usr/lib/python2.6/site-packages/barman/cli.py", line 411, in recover
    remote_command=args.remote_ssh_command)
  File "/usr/lib/python2.6/site-packages/barman/server.py", line 1164, in recover
    target_xid, target_name, exclusive, remote_command)
  File "/usr/lib/python2.6/site-packages/barman/backup.py", line 445, in recover
    exclusive, remote_command)
  File "/usr/lib/python2.6/site-packages/barman/recovery_executor.py", line 229, in recover
    self._analyse_temporary_config_files(recovery_info)
  File "/usr/lib/python2.6/site-packages/barman/recovery_executor.py", line 884, in _analyse_temporary_config_files
    "%s.origin" % conf_file)
  File "/usr/lib/python2.6/site-packages/barman/recovery_executor.py", line 946, in _pg_config_mangle
    with open(filename, 'w') as f:
IOError: [Errno 13] Permission denied: '/tmp/barman_recovery-Yd5gHN/postgresql.conf'
```

file:
```
[root@barman-qa-01 barman_recovery-Yd5gHN]# ls -la /tmp/barman_recovery-Yd5gHN/postgresql.conf
-r--r--r-- 1 barman barman 758 Nov  7 12:44 /tmp/barman_recovery-Yd5gHN/postgresql.conf
```

my system:
```
[root@barman-qa-01 ~]# cat /etc/redhat-release
CentOS release 6.5 (Final)
[root@barman-qa-01 ~]# python --version
Python 2.6.6
[root@barman-qa-01 ~]# rpm -aq *barman*
barman-2.0-1.rhel6.noarch
```

**Comment by mnencia** [comment]
What version of barman you are using?

Could you please attach the permission of the enclosing directory?

```
ls -la /tmp/barman_recovery-Yd5gHN/
```

**Comment by jacekjaros** [comment]
Hi @mnencia 

```
[root@barman-qa-01 ~]# ls -la /tmp/barman_recovery-Yd5gHN/
total 20
drwx------ 2 barman barman 4096 Nov  8 15:38 .
drwxrwxrwt 6 root   root   4096 Nov  8 18:33 ..
-rw-r--r-- 1 barman barman    0 Nov  8 15:38 0000000100000002000000B2.done
-rw-r--r-- 1 barman barman    0 Nov  8 15:38 0000000100000002000000B3.done
-rw-r--r-- 1 barman barman    0 Nov  8 15:38 0000000100000002000000B4.done
-rw------- 1 barman barman   88 Nov  7 12:44 postgresql.auto.conf
-r--r--r-- 1 barman barman  758 Nov  7 12:44 postgresql.conf
-r--r--r-- 1 barman barman  758 Nov  7 12:44 postgresql.conf.origin
```

**Comment by mnencia** [comment]
Could you please check the permissions of the postgresql.conf in your source PostgreSQL data directory? My guess is that it is read-only, and, given that Barman preserver permissions, it would explain why Barman cannot modify it during the recovery.

**Comment by jacekjaros** [comment]
You are right about permission at source server.
Is this meant that read only files restore is not supported ?

**Comment by mnencia** [comment]
At the moment, having a read-only postgresql.conf is not supported. I'm marking it as bug because we should support it or at least give an informative error message.
